### PR TITLE
TS-126 - Subtracting pending days from total holidays

### PR DESCRIPTION
**Pull request by mcromie92**
REMOVING PENDING DAYS FROM TOTAL HOLIDAYS ON THE PROFILE VIEW TO MAKE THIS LESS CONFUSING TO USER REQUESTING DAYS OFF

### CODE REVIEW

**Comment by ghost** [comment]
> REMOVING PENDING DAYS FROM TOTAL HOLIDAYS ON THE PROFILE VIEW TO MAKE THIS LESS CONFUSING TO USER REQUESTING DAYS OFF

Are you shouting here Michaela?

**Comment by mcromie92** [comment]
haha @girwin575 does look like it lol apologises about the caps :)

**Review by lee-cheung — APPROVED** [review]
looks good

**Review by William-Unosquare — COMMENTED** [review]
Looks good 👌🏻

**Pull request merged**
