### PR TITLE
Styling update team selection

### PR DESCRIPTION
**Pull request by paulmatchett**
Update to team selection now has Unosquare blue links with active states

Before:
image

After:
image

Updated:
image

### CODE REVIEW

**Comment by William-Unosquare** [comment]
Not sure if I agree on all the styling changes here. The buttons that are just a border look a bit off to me. One thing though to definitely fix from the screenshot is to bring the client name closer to the teams to tie them together. The client name currently looks a little lost up there.

**Comment by paulmatchett** [comment]
William the colour of the team links were green and had no active styles attached? This was bad usability. I can move the list of teams back up and closer to the client if required, but I felt it was all too squashed the way it was.

**Comment by William-Unosquare** [comment]
I agree with adding active styling of course.  I'd definitely move the client name down closer to the teams that it concerns so there is a relationship tying them together through close proximity. Right now it feels like there's no relationship between the teams and the client.

https://www.interaction-design.org/literature/article/laws-of-proximity-uniform-connectedness-and-continuation-gestalt-principles-2

**Review by William-Unosquare — APPROVED** [review]
Looks far better now :)

**Pull request merged**
